apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
spec:
  selector:
    app: product-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

