apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
      - name: flask-container
        image: gcr.io/rishab-gupta-cwx-internal/product-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "postgres_test"
        - name: DB_PASSWORD
          value: "rishab1903"
        - name: DB_HOST
          value: "10.22.112.19"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "products_test"
        - name: API_TOKEN
          value: "mysecrettoken123"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20


