name: Build and Push Frontend to GCR

on:
  push:
    branches: [branch_2]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/332413712515/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@rishab-gupta-cwx-internal.iam.gserviceaccount.com'

      - name: Configure Docker to use gcloud credentials
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker Image to GCR
        run: |
          docker build -t gcr.io/rishab-gupta-cwx-internal/product-frontend:latest .
          docker push gcr.io/rishab-gupta-cwx-internal/product-frontend:latest

